AllCops:
  TargetRubyVersion: 2.6.3
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - config/initializers/*
    - bin/**/*
    - db/**/*

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: true
  PreferredDelimiters:
    '%i': '()'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120
  Exclude:
    - spec/**/*
