AllCops:
  TargetRubyVersion: 2.6.3
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
    - config/initializers/*
    - bin/**/*
    - db/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 120
  Exclude:
    - spec/**/*
